# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Angular JS setup

on:
   workflow_dispatch:

jobs:
  Setup-Angular-app:
    runs-on: ubuntu-latest
    environment:
      name: development
      url: ${{ steps.get-url.outputs.your_site }}

    steps:
    - run: echo "Setting up Nodejs"
    - name: checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: use node.js v14 
      uses: actions/setup-node@v1
      with:
        node-version: '14'
        check-latest: true
        registry-url: https://registry.npmjs.org/
    
    - name: "Install angular code"
      run: |
        npm install - g @angular/cli
        
    - name: "Generate Angular code"
      run: ng new myNewApp
      
